---
name: Code Coverage 🛠

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  coverage:
    name: Coverage 📔
    uses: insightsengineering/r.pkg.template/.github/workflows/test-coverage.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      publish-coverage-report-gh-pages: false
